### ISSUE TITLE
Error aftr install: IdM

### ISSUE THREAD

**Issue by slain2** [HewlettPackard/codar-ce#1]
Installed as per instructions for docker...then
https://192.168.1.137:18444/csa
gives error "Unable to connect to IdM service. Please contact your system administrator"
https://192.168.1.137:18444/csa/login?login_error=6

Regards,
Slain2

**Comment by slain2** [comment]
Forget the aboe IdM issue - I had not waited long enough for the services to start up.

**Comment by zydycjr** [comment]
Hi Slain2  how did you start Idm service? I waited 1day still showing the issue
